export const categories: Record<string, string[]> = {
  Harmlos: [
    'Ich hab noch nie im Regen getanzt.',
    'Ich hab noch nie die Schule geschwänzt.',
    'Ich hab noch nie eine Prüfung ohne zu lernen bestanden.',
    'Ich hab noch nie aus Versehen eine Nachricht an die falsche Person geschickt.',
    'Ich hab noch nie über meinen eigenen Witz am lautesten gelacht.',
    'Ich hab noch nie mich in der Öffentlichkeit hingelegt (gestolpert oder gefallen).',
    'Ich hab noch nie auf einer Party in komplett falscher Kleidung aufgetaucht.',
    'Ich hab noch nie eine Berühmtheit getroffen und mich dabei total dumm verhalten.',
    'Ich hab noch nie ein Haustier vermenschlicht und mit ihm geredet wie mit einem Menschen.',
    'Ich hab noch nie mich in einer Bar- oder Club-Toilette eingesperrt.',
  ],
  Frech: [
    'Ich hab noch nie mit jemandem aus dieser Runde geflirtet.',
    'Ich hab noch nie eine Notlüge benutzt, um eine Verabredung abzusagen.',
    'Ich hab noch nie jemanden geghostet.',
    'Ich hab noch nie betrunken meinem Ex geschrieben.',
    'Ich hab noch nie auf einem ersten Date eingeschlafen.',
    'Ich hab noch nie jemanden in dieser Runde schon mal geküsst.',
    'Ich hab noch nie mich in eine vergebene Person verliebt.',
    'Ich hab noch nie ein Nacktfoto verschickt.',
    'Ich hab noch nie mit dem Handy einer anderen Person heimlich rumgeschnüffelt.',
    'Ich hab noch nie so getan, als würde ich jemanden nicht kennen, um eine Begegnung zu vermeiden.',
  ],
  Spicy: [
    'Ich hab noch nie im Auto mehr als nur geküsst.',
    'Ich hab noch nie eine Affäre mit einer vergebenen Person gehabt.',
    'Ich hab noch nie an einem One-Night-Stand teilgenommen.',
    'Ich hab noch nie an einem ungewöhnlichen Ort intim geworden (nicht im Bett).',
    'Ich hab noch nie etwas mit dem Ex/der Ex einer Person aus dieser Runde gehabt.',
    'Ich hab noch nie jemanden mit nach Hause genommen, ohne den Namen zu kennen.',
    'Ich hab noch nie mir während einer intimen Situation etwas Peinliches passiert.',
    'Ich hab noch nie jemandem aus dieser Runde schon mal etwas Verruchtes geschrieben.',
    'Ich hab noch nie mit mehr als einer Person am selben Abend etwas gehabt.',
    'Ich hab noch nie Sexspielzeug benutzt.',
  ],
}
