export const categories: Record<string, string[]> = {
  Essen: [
    'Pizza',
    'Sushi',
    'Döner',
    'Currywurst',
    'Spaghetti',
    'Schnitzel',
    'Burger',
    'Pommes',
    'Lasagne',
    'Pfannkuchen',
    'Erdbeere',
    'Schokolade',
    'Popcorn',
    'Käsekuchen',
    'Gulasch',
  ],
  Tiere: [
    'Elefant',
    'Pinguin',
    'Löwe',
    'Delfin',
    'Giraffe',
    'Krokodil',
    'Papagei',
    'Känguru',
    'Faultier',
    'Eule',
    'Hai',
    'Fuchs',
    'Igel',
    'Waschbär',
    'Oktopus',
  ],
  Berufe: [
    'Feuerwehrmann',
    'Arzt',
    'Lehrer',
    'Pilot',
    'Koch',
    'Friseur',
    'Anwalt',
    'Bäcker',
    'Polizist',
    'Astronaut',
    'Zahnarzt',
    'Gärtner',
    'Elektriker',
    'Fotograf',
    'Schauspieler',
  ],
  Orte: [
    'Strand',
    'Flughafen',
    'Bibliothek',
    'Krankenhaus',
    'Schwimmbad',
    'Friedhof',
    'Kino',
    'Bergwerk',
    'Zoo',
    'Konzert',
    'Wüste',
    'U-Bahn',
    'Kirche',
    'Fußballstadion',
    'Weltraum',
  ],
  Filme: [
    'Titanic',
    'Der König der Löwen',
    'Star Wars',
    'Harry Potter',
    'Jurassic Park',
    'Findet Nemo',
    'Der Pate',
    'Fluch der Karibik',
    'Toy Story',
    'Avatar',
    'Frozen',
    'Inception',
    'Matrix',
    'Shrek',
    'Joker',
  ],
  Gegenstände: [
    'Regenschirm',
    'Zahnbürste',
    'Kopfhörer',
    'Rucksack',
    'Feuerzeug',
    'Spiegel',
    'Kerze',
    'Wecker',
    'Schere',
    'Taschenlampe',
    'Portemonnaie',
    'Kissen',
    'Brille',
    'Gitarre',
    'Handtuch',
  ],
}

export const allCategoryNames = Object.keys(categories)
