export const categories: Record<string, string[]> = {
  Lustig: [
    'Wer würde eher bei einem Zombie-Angriff als Erstes sterben?',
    'Wer würde eher zum Mond fliegen, wenn es möglich wäre?',
    'Wer würde eher auf eine einsame Insel die völlig falschen Sachen mitnehmen?',
    'Wer würde eher im Fernsehen landen, ohne es zu merken?',
    'Wer würde eher einen Rap-Battle gewinnen?',
    'Wer würde eher im falschen Zug einschlafen und in einer anderen Stadt aufwachen?',
    'Wer würde eher bei einem Feueralarm als Letztes das Gebäude verlassen?',
    'Wer würde eher ein Reality-TV-Format gewinnen?',
    'Wer würde eher sich beim ersten Date verlaufen?',
    'Wer würde eher seinen Job kündigen, um Influencer zu werden?',
  ],
  Frech: [
    'Wer würde eher heimlich in eine Person aus dieser Runde verliebt sein?',
    'Wer würde eher seinen Ex/seine Ex stalken?',
    'Wer würde eher bei einem Date die Rechnung nicht zahlen?',
    'Wer würde eher jemanden aus dieser Runde daten?',
    'Wer würde eher aus Eifersucht das Handy des Partners checken?',
    'Wer würde eher auf einer Hochzeit den Heiratsantrag versauen?',
    'Wer würde eher eine Affäre anfangen?',
    'Wer würde eher seine Beziehung wegen eines Jobs beenden?',
    'Wer würde eher bei einer Dating-App nach links UND rechts swipen, nur um zu sehen was passiert?',
    'Wer würde eher mit dem Ex/der Ex von jemandem aus dieser Runde flirten?',
  ],
  Spicy: [
    'Wer würde eher an einem Dreier teilnehmen?',
    'Wer würde eher Sex am Arbeitsplatz haben?',
    'Wer würde eher eine Affäre mit dem Chef/der Chefin haben?',
    'Wer würde eher ein riskantes Nacktfoto verschicken?',
    'Wer würde eher in dieser Runde am ehesten eine Affäre anfangen?',
    'Wer würde eher bei einer Verabredung sofort ins Bett gehen?',
    'Wer würde eher einen Fetisch haben, von dem niemand weiß?',
    'Wer würde eher eine riskante Mutprobe im Bett annehmen?',
    'Wer würde eher für eine Nacht mit einer Berühmtheit alles stehen und liegen lassen?',
    'Wer würde eher jemanden aus dieser Runde küssen, wenn ein Spiel es verlangt?',
  ],
}
